newPRWelcomeComment: >
  Thank you ğŸ‰ for opening this pull request!ğŸ’–
  Please make sure you have followed our Contributing Guidelines.ğŸ™Œ
  We will test out your code and reply in a bit with some pointers and requests.ğŸ’¿
  There may be some errors, **but don't worry!** We'll work through them with you! ğŸ‘ğŸ‰ğŸ˜„
  If you haven't filled the template out, Please do so!ğŸš€


firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ™ŒğŸ‰âš¡ï¸
  Now that you've merged your first pull request, you're the perfect person to help someone else out with this challenging first step.ğŸ˜„ğŸ™Œ


newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  Thank you and congratsğŸ‰ for opening your very first issue in this project. Please adhere to our Code of Conduct.
  Please make sure not to start working on the issue, unless you get assigned to it.ğŸ˜„